class GlobalParameters:
    seed = 'seed'
    root = 'root'
    experiment = 'experiment'
    data_set = 'data_set'
    target = 'target'
    partition_data = 'partition_data'
    preprocessed_data = 'preprocessed_data'
    preprocessed_training_data = 'preprocessed_training_data'
    input_dimensions = 'input_dimensions'
    n = 'n'
    saliency_map_substructures_data = 'saliency_map_substructures_data'
    feature_id = 'feature_id'
    shared_network = 'shared_network'
    transfer_data_sets = 'transfer_data_sets'
